[build]
  command = "npm run build"
  publish = "build"
  environment = { NODE_VERSION = "18" }

[build.environment]
  NODE_ENV = "production"
  CI = "false"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200 